# Jekyll config for the site
title: "Jaelin Lee - MLOps Engineer | AI Product & Governance Strategist"
description: "Production-grade machine learning with system thinking and responsible deployment."
url: "https://jaelin215.github.io"
baseurl: ""
image: /img/ai_alignment.png

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 

# Markdown / kramdown settings
markdown: kramdown
kramdown:
  input: GFM

# Permalinks, excluding files, etc.
permalink: /:categories/:title/
exclude:
  - Gemfile
  - Gemfile.lock
